### ISSUE TITLE
GT3 chasse cam placement 

### ISSUE THREAD

**Issue by pouya07591** [TheAdmiester/PCSX2-Cheats#1]
Hello can you please make gt3 chase camera placement pnach for gt4 online beta?

**Comment by TheAdmiester** [comment]
Already exists: https://github.com/AeroWidescreen/PCSX2-Cheats/blob/main/Gran%20Turismo%204/SCUS-97436%20(GT4%20Online%20Public%20Beta)/GT3%20Camera%20Placement/SCUS-97436_32A1C752_gt3camplacement.pnach

**Comment by pouya07591** [comment]
> Already exists: https://github.com/AeroWidescreen/PCSX2-Cheats/blob/main/Gran%20Turismo%204/SCUS-97436%20(GT4%20Online%20Public%20Beta)/GT3%20Camera%20Placement/SCUS-97436_32A1C752_gt3camplacement.pnach

thanks a lot, i searched for a while but i couldn't find it, sorry
